name : First workflow
on : push
jobs:
    first_job:
          runs_on: ubuntu-latest
          steps:
          - name : Welcome msg
            run: "My first job"
          
          - name: List files
            run: ls

          - name: Read file
            run: cat

          