name: First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome msg
        run: echo "My first job"

      - name: Running shell script
        run: | 
             chmod +x ../app.sh
             ./app.sh

