name: First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show all files (debug)
        run: ls -R

      - name: Run shell script
        run: |
          chmod +x app.sh
          ./app.sh


