jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        env:
          MESSAGE: "Hello from step 1"
        run: echo "$MESSAGE"

      - name: Step 2
        run: echo "$MESSAGE"
