name: Dummy CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dummy Build Step
        run: |
          echo "🔧 Building the project..."
          echo "Build complete!"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dummy Test Step
        run: |
          echo "🧪 Running tests..."
          echo "All tests passed!"

  deploy:
    runs-on: ubuntu-latest
    needs: [test , build ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dummy Deploy Step
        run: |
          echo "🚀 Deploying the app..."
          echo "Deployment successful!"
